### PR TITLE
Change device name

### PR DESCRIPTION
**Pull request by PatrikMatiasko**

### CODE REVIEW

**Comment by jkralik** [comment]
After I own the device and change the device name it is change ownership status as unowned (F5 button - fix it). Could you fix the issue ?

Look to attached video:
https://user-images.githubusercontent.com/23374974/178099028-3e3e40c7-11df-4c8b-80f6-3673d3c51121.mp4

**Review by jkralik — COMMENTED** [review]
Previous comment

**Comment by PatrikMatiasko** [comment]
> After I own the device and change the device name it is change ownership status as unowned (F5 button - fix it). Could you fix the issue ?
> 
> Look to attached video: https://user-images.githubusercontent.com/23374974/178099028-3e3e40c7-11df-4c8b-80f6-3673d3c51121.mp4

I found and fix issue about handling own state.

**Review by jkralik — APPROVED** [review]
Yes. It works. Thx

**Pull request merged**
