### PR TITLE
Pm/new design

### PR DESCRIPTION
**Pull request by PatrikMatiasko**

### CODE REVIEW

**Comment by jkralik** [comment]
In tree view I'm not able to click to the link:
image

**Comment by jkralik** [comment]
When I own device the page is not refreshed (device is still unowned). Need to press F5.

**Comment by jkralik** [comment]
Delete button is not connected to the action (It shows device details).
image

**Comment by jkralik** [comment]
Resource path is not included in URI when I open it.
image

BTW: when I put URI with resource path it opens correctly the resource page.

**Comment by jkralik** [comment]
Unowned status
image

**Comment by jkralik** [comment]
Migrate onboarding modal window to new design + allow to `paste all` data:
image

**Comment by jkralik** [comment]
Pls

- rename `Mass import` to `Paste all`
- is it possible to hide the edit component for `Paste all` ? When you click to paste all of it just fill in all properties below. 

image

**Comment by jkralik** [comment]
@PatrikMatiasko 
Pls fix tree view: oic/d and oic/res are not visible in tree view
image

**Comment by jkralik** [comment]
@PatrikMatiasko 
The redirect URL is not working eg:
http://212.89.237.161:50080/devices/ee1eaac2-cc12-433a-739a-0b90059e4b95
will open window with devices - not certain device

**Comment by jkralik** [comment]
@PatrikMatiasko For unsecured devices ("ownership Status: unsupported") the Own/Disown buttons are not meaningful.
image

**Comment by jkralik** [comment]
Pls remove the ownership status for the device that has unsupported value:
image

**Comment by PatrikMatiasko** [comment]
> 3 co

We have a condition for display in the tree. Row is visible, whew: canBeResourceEdited(endpointInformations) || isOwned
 from the past. Can I change it?

**Comment by jkralik** [comment]
When another user login to client-application than he need to see page that the app is used by someone else - currently he see empty screen:
image

**Comment by jkralik** [comment]
Hide own buttons + instead of `unowned` use `unsupported` with gray color
image

**Comment by jkralik** [comment]
> [> 3 co](https://github.com/plgd-dev/client-application/pull/130#issuecomment-1637519304)
> 
> We have a condition for display in the tree. Row is visible, whew: canBeResourceEdited(endpointInformations) || isOwned from the past. Can I change it?
> 
> `export const canBeResourceEdited = (endpoints?: { endpoint: string }[]) => endpoints && endpoints.some( (e: { endpoint: string }) => e.endpoint.indexOf('coap://') > -1 || e.endpoint.indexOf('coap+tcp://') > -1 )`
> 
> UPDATE: I have solution, you can check with new commit

Yes it works :)

When I look to function `canBeResourceEdited` is see it in two places:

web/src/containers/Devices/utils.ts:36
web/packages/shared-ui/src/stories/Table/TreeTable.stories.jsx:27

pls could you deduplicate it ?

**Comment by PatrikMatiasko** [comment]
> > [> 3 co](https://github.com/plgd-dev/client-application/pull/130#issuecomment-1637519304)
> > We have a condition for display in the tree. Row is visible, whew: canBeResourceEdited(endpointInformations) || isOwned from the past. Can I change it?
> > `export const canBeResourceEdited = (endpoints?: { endpoint: string }[]) => endpoints && endpoints.some( (e: { endpoint: string }) => e.endpoint.indexOf('coap://') > -1 || e.endpoint.indexOf('coap+tcp://') > -1 )`
> > UPDATE: I have solution, you can check with new commit
> 
> Yes it works :)
> 
> When I look to function `canBeResourceEdited` is see it in two places:
> 
> web/src/containers/Devices/utils.ts:36 web/packages/shared-ui/src/stories/Table/TreeTable.stories.jsx:27
> 
> pls could you deduplicate it ?

It should work as it is. :)

**Review by jkralik — APPROVED** [review]

**Pull request merged**
