### PR TITLE
Shared UI

### PR DESCRIPTION
**Pull request by PatrikMatiasko**

### CODE REVIEW

**Comment by jkralik** [comment]
There is some issue with build UI: https://github.com/plgd-dev/client-application/runs/7981879810?check_suite_focus=true

**Review by jkralik — COMMENTED** [review]
https://github.com/plgd-dev/client-application/runs/7981879810?check_suite_focus=true https://github.com/plgd-dev/client-application/runs/7981879810?check_suite_focus=true

**Comment by jkralik** [comment]
Pls could you fix the build issue and remove smells?

Creating an optimized production build...
Failed to compile.

``` bash
./src/index.tsx
Cannot find module: '@shared-ui/components/new/IntlProvider'. Make sure this package is installed.
```

**Comment by PatrikMatiasko** [comment]
> Pls could you fix the build issue and remove smells?
> 
> Creating an optimized production build... Failed to compile.
> 
> ```shell
> ./src/index.tsx
> Cannot find module: '@shared-ui/components/new/IntlProvider'. Make sure this package is installed.
> ```

shared-ui is submodule of this repo. Is submodule checked out ?

**Comment by jkralik** [comment]
> 
Hm it seems not. It is always starts with clean system - what nodejs version it is needed to build it?

**Comment by jkralik** [comment]
Pls fix viewed content:
image

**Review by jkralik — COMMENTED** [review]
Preview comment

**Pull request merged**
